channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3
  - perl-xml-libxml==2.0132
  - tar==1.32
  - binutils==2.35
  - fates-emerald==2.0.1
  - xarray
  - matplotlib
  - netcdf4
  - cartopy
  - dask
